# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gamer/Desktop/AquiumOS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gamer/Desktop/AquiumOS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gamer/Desktop/AquiumOS/CMakeFiles /home/gamer/Desktop/AquiumOS//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gamer/Desktop/AquiumOS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named startAQ.so

# Build rule for target.
startAQ.so: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 startAQ.so
.PHONY : startAQ.so

# fast build rule for target.
startAQ.so/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/startAQ.so.dir/build.make CMakeFiles/startAQ.so.dir/build
.PHONY : startAQ.so/fast

#=============================================================================
# Target rules for targets named installer_dep.so

# Build rule for target.
installer_dep.so: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 installer_dep.so
.PHONY : installer_dep.so

# fast build rule for target.
installer_dep.so/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/installer_dep.so.dir/build.make CMakeFiles/installer_dep.so.dir/build
.PHONY : installer_dep.so/fast

#=============================================================================
# Target rules for targets named init_gameros.so

# Build rule for target.
init_gameros.so: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 init_gameros.so
.PHONY : init_gameros.so

# fast build rule for target.
init_gameros.so/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_gameros.so.dir/build.make CMakeFiles/init_gameros.so.dir/build
.PHONY : init_gameros.so/fast

#=============================================================================
# Target rules for targets named launchd.so

# Build rule for target.
launchd.so: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 launchd.so
.PHONY : launchd.so

# fast build rule for target.
launchd.so/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/launchd.so.dir/build.make CMakeFiles/launchd.so.dir/build
.PHONY : launchd.so/fast

#=============================================================================
# Target rules for targets named System_Services.so

# Build rule for target.
System_Services.so: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 System_Services.so
.PHONY : System_Services.so

# fast build rule for target.
System_Services.so/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/System_Services.so.dir/build.make CMakeFiles/System_Services.so.dir/build
.PHONY : System_Services.so/fast

src/System_Services.o: src/System_Services.cpp.o
.PHONY : src/System_Services.o

# target to build an object file
src/System_Services.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/System_Services.so.dir/build.make CMakeFiles/System_Services.so.dir/src/System_Services.cpp.o
.PHONY : src/System_Services.cpp.o

src/System_Services.i: src/System_Services.cpp.i
.PHONY : src/System_Services.i

# target to preprocess a source file
src/System_Services.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/System_Services.so.dir/build.make CMakeFiles/System_Services.so.dir/src/System_Services.cpp.i
.PHONY : src/System_Services.cpp.i

src/System_Services.s: src/System_Services.cpp.s
.PHONY : src/System_Services.s

# target to generate assembly for a file
src/System_Services.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/System_Services.so.dir/build.make CMakeFiles/System_Services.so.dir/src/System_Services.cpp.s
.PHONY : src/System_Services.cpp.s

src/Window_Manager.o: src/Window_Manager.cpp.o
.PHONY : src/Window_Manager.o

# target to build an object file
src/Window_Manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/startAQ.so.dir/build.make CMakeFiles/startAQ.so.dir/src/Window_Manager.cpp.o
.PHONY : src/Window_Manager.cpp.o

src/Window_Manager.i: src/Window_Manager.cpp.i
.PHONY : src/Window_Manager.i

# target to preprocess a source file
src/Window_Manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/startAQ.so.dir/build.make CMakeFiles/startAQ.so.dir/src/Window_Manager.cpp.i
.PHONY : src/Window_Manager.cpp.i

src/Window_Manager.s: src/Window_Manager.cpp.s
.PHONY : src/Window_Manager.s

# target to generate assembly for a file
src/Window_Manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/startAQ.so.dir/build.make CMakeFiles/startAQ.so.dir/src/Window_Manager.cpp.s
.PHONY : src/Window_Manager.cpp.s

src/init_window.o: src/init_window.cpp.o
.PHONY : src/init_window.o

# target to build an object file
src/init_window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_gameros.so.dir/build.make CMakeFiles/init_gameros.so.dir/src/init_window.cpp.o
.PHONY : src/init_window.cpp.o

src/init_window.i: src/init_window.cpp.i
.PHONY : src/init_window.i

# target to preprocess a source file
src/init_window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_gameros.so.dir/build.make CMakeFiles/init_gameros.so.dir/src/init_window.cpp.i
.PHONY : src/init_window.cpp.i

src/init_window.s: src/init_window.cpp.s
.PHONY : src/init_window.s

# target to generate assembly for a file
src/init_window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_gameros.so.dir/build.make CMakeFiles/init_gameros.so.dir/src/init_window.cpp.s
.PHONY : src/init_window.cpp.s

src/installer_dep.o: src/installer_dep.cpp.o
.PHONY : src/installer_dep.o

# target to build an object file
src/installer_dep.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/installer_dep.so.dir/build.make CMakeFiles/installer_dep.so.dir/src/installer_dep.cpp.o
.PHONY : src/installer_dep.cpp.o

src/installer_dep.i: src/installer_dep.cpp.i
.PHONY : src/installer_dep.i

# target to preprocess a source file
src/installer_dep.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/installer_dep.so.dir/build.make CMakeFiles/installer_dep.so.dir/src/installer_dep.cpp.i
.PHONY : src/installer_dep.cpp.i

src/installer_dep.s: src/installer_dep.cpp.s
.PHONY : src/installer_dep.s

# target to generate assembly for a file
src/installer_dep.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/installer_dep.so.dir/build.make CMakeFiles/installer_dep.so.dir/src/installer_dep.cpp.s
.PHONY : src/installer_dep.cpp.s

src/launchd.o: src/launchd.cpp.o
.PHONY : src/launchd.o

# target to build an object file
src/launchd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/launchd.so.dir/build.make CMakeFiles/launchd.so.dir/src/launchd.cpp.o
.PHONY : src/launchd.cpp.o

src/launchd.i: src/launchd.cpp.i
.PHONY : src/launchd.i

# target to preprocess a source file
src/launchd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/launchd.so.dir/build.make CMakeFiles/launchd.so.dir/src/launchd.cpp.i
.PHONY : src/launchd.cpp.i

src/launchd.s: src/launchd.cpp.s
.PHONY : src/launchd.s

# target to generate assembly for a file
src/launchd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/launchd.so.dir/build.make CMakeFiles/launchd.so.dir/src/launchd.cpp.s
.PHONY : src/launchd.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... System_Services.so"
	@echo "... init_gameros.so"
	@echo "... installer_dep.so"
	@echo "... launchd.so"
	@echo "... startAQ.so"
	@echo "... src/System_Services.o"
	@echo "... src/System_Services.i"
	@echo "... src/System_Services.s"
	@echo "... src/Window_Manager.o"
	@echo "... src/Window_Manager.i"
	@echo "... src/Window_Manager.s"
	@echo "... src/init_window.o"
	@echo "... src/init_window.i"
	@echo "... src/init_window.s"
	@echo "... src/installer_dep.o"
	@echo "... src/installer_dep.i"
	@echo "... src/installer_dep.s"
	@echo "... src/launchd.o"
	@echo "... src/launchd.i"
	@echo "... src/launchd.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

